alter table if exists public.elsayed
    add column if not exists "عدد المحاولات" integer not null default 0,
    add column if not exists "آخر محاولة تواصل" timestamptz,
    add column if not exists "آخر وسيلة تواصل" text;

create table if not exists public.calls_log (
    id bigint generated by default as identity primary key,
    shipment_id bigint,
    shipment_code text,
    rep_name text,
    actor_name text,
    actor_role text,
    contact_method text not null,
    contact_phone text,
    result text,
    created_at timestamptz not null default timezone('utc', now())
);

create index if not exists calls_log_shipment_id_idx on public.calls_log (shipment_id);
create index if not exists calls_log_created_at_idx on public.calls_log (created_at desc);
